### ISSUE TITLE
Crash when searching tags via AcoustID source

### ISSUE THREAD

**Issue by sizeofvoid** [puddletag/puddletag#564]
Steps to reproduce:

- Windows / tick "Tag sources"
- Open a dir containing an album
- Select all files in the album
- In the "Tag sources" window set source to AcoustID
- Click the Search button

This works in 1.2.0, and fails like so in 2.0.1. FreeDB and MusicBrainz works fine.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/tagsources/acoust_id.py", line 108, in fingerprint_file
    return acoustid._fingerprint_file_fpcalc(fn, 120)
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/tagsources/_acoustid.py", line 299, in _fingerprint_file_fpcalc
    parts = line.split('=', 1)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/webdb.py", line 866, in search
    return tag_source_search(self.curSource, group, files)
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/webdb.py", line 557, in tag_source_search
    albums = ts.search(primary, group[primary])
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/tagsources/acoust_id.py", line 314, in search
    data, fp = match("gT8GJxhO", fn.filepath, fp, dur)
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/tagsources/acoust_id.py", line 135, in match
    dur, fp = fingerprint_file(path)
  File "/usr/local/lib/python3.8/site-packages/puddlestuff/tagsources/acoust_id.py", line 110, in fingerprint_file
    return acoustid._fingerprint_file_fpcalc(fn)
TypeError: _fingerprint_file_fpcalc() missing 1 required positional argument: 'maxlength'
```
